### PR TITLE
Added index.html and style.css Issue #10

### PR DESCRIPTION
**Pull request by dhananjay8968**
Made index.html and style.css . Linked style.css to index.html

### CODE REVIEW

**Comment by fury-coder** [comment]
invalid html code showing empty page..and css is also empty file..not accepted

**Comment by dhananjay8968** [comment]
It is not mentioned what should be included in the html and css . Please elaborate on that part . It was not mentioned hence I pushed an empty html and css file.

**Comment by dhananjay8968** [comment]
and why spam label is added

**Comment by dhananjay8968** [comment]
You provided the description late . I worked as per the previous description provided. @fury-coder

**Comment by SugatoBagchi** [comment]
If you cannot maintain a repository, then don't @fury-coder . But don't lurk around providing incorrect details and then labelling PRs as SPAM. He worked according to your instructions.

**Pull request closed without merging**
